import { Request, Response, NextFunction } from 'express';
import { teacherService } from '../services/teacher.service';
import { auditLogService } from '../services/audit-log.service';
import { notificationService } from '../services/notification.service';
import { prisma } from '../config/database';
import { successResponse } from '../utils/response';
import type {
  CreateTeacherInput,
  UpdateTeacherInput,
} from '../validators/teacher.validator';

export const teacherController = {
  /**
   * GET /api/v1/teachers
   * List all teachers. Proprietor only.
   */
  async list(_req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const teachers = await teacherService.getTeachers();
      res.status(200).json(successResponse(teachers));
    } catch (error) {
      next(error);
    }
  },

  /**
   * GET /api/v1/teachers/:id
   * Get a single teacher.
   */
  async getById(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const teacher = await teacherService.getTeacherById(String(req.params.id));
      res.status(200).json(successResponse(teacher));
    } catch (error) {
      next(error);
    }
  },

  /**
   * GET /api/v1/teachers/me
   * Get the teacher record for the currently logged-in user.
   */
  async me(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      if (!req.user) {
        res.status(401).json({ success: false, error: 'Unauthorized', message: 'Authentication required', statusCode: 401 });
        return;
      }
      const teacher = await teacherService.getTeacherByUserId(req.user.userId);
      res.status(200).json(successResponse(teacher));
    } catch (error) {
      next(error);
    }
  },

  /**
   * POST /api/v1/teachers
   * Create a new teacher. Proprietor only.
   */
  async create(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const input = req.body as CreateTeacherInput;
      const teacher = await teacherService.createTeacher(input);
      res.status(201).json(successResponse(teacher, 'Teacher created successfully'));
    } catch (error) {
      next(error);
    }
  },

  /**
   * PATCH /api/v1/teachers/:id
   * Update a teacher.
   */
  async update(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const input = req.body as UpdateTeacherInput;
      const teacher = await teacherService.updateTeacher(String(req.params.id), input);
      res.status(200).json(successResponse(teacher, 'Teacher updated successfully'));
    } catch (error) {
      next(error);
    }
  },

  /**
   * PATCH /api/v1/teachers/:id/suspend
   * Suspend a teacher.
   */
  async suspend(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const teacher = await teacherService.suspendTeacher(String(req.params.id));
      res.status(200).json(successResponse(teacher, 'Teacher suspended'));
    } catch (error) {
      next(error);
    }
  },

  /**
   * PATCH /api/v1/teachers/:id/activate
   * Reactivate a teacher.
   */
  async activate(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const teacher = await teacherService.activateTeacher(String(req.params.id));
      res.status(200).json(successResponse(teacher, 'Teacher activated'));
    } catch (error) {
      next(error);
    }
  },

  /**
   * POST /api/v1/teachers/:id/reset-password
   * Reset a teacher's password. Notifies the teacher and writes an
   * audit log entry.
   */
  async resetPassword(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { newPassword } = req.body || {};
      const result = await teacherService.resetPassword(String(req.params.id), newPassword);
      res.status(200).json(successResponse(result, 'Password reset successfully'));

      if (req.user) {
        // Audit log + teacher notification (best-effort)
        const teacher = await prisma.teacher.findUnique({
          where: { id: String(req.params.id) },
          select: { id: true, userId: true, email: true, firstName: true, lastName: true },
        });
        if (teacher) {
          auditLogService
            .log({
              userId: req.user.userId,
              userEmail: req.user.email,
              action: 'TEACHER_PASSWORD_RESET',
              entityType: 'Teacher',
              entityId: teacher.id,
              payload: { teacherEmail: teacher.email, autoGenerated: !newPassword },
              ip: req.ip,
              userAgent: req.get('user-agent') ?? undefined,
            })
            .catch(() => {});

          notificationService
            .push({
              userId: teacher.userId,
              title: 'Password reset',
              body: `Your password was reset by ${req.user.email}. New password: ${result.newPassword}`,
              link: '/login',
            })
            .catch(() => {});
        }
      }
    } catch (error) {
      next(error);
    }
  },

  /**
   * DELETE /api/v1/teachers/:id
   * Soft-delete a teacher (suspend). Hard delete is not allowed to preserve
   * historical academic records.
   */
  async delete(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const teacher = await teacherService.suspendTeacher(String(req.params.id));
      res.status(200).json(successResponse(teacher, 'Teacher deleted (suspended)'));
    } catch (error) {
      next(error);
    }
  },

  /**
   * GET /api/v1/teachers/search?q=:query
   * Search teachers.
   */
  async search(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const query =
        (req.query.q as string) ||
        ((res.locals as Record<string, unknown>).query as { q?: string })?.q ||
        '';
      const teachers = await teacherService.searchTeachers(query);
      res.status(200).json(successResponse(teachers));
    } catch (error) {
      next(error);
    }
  },
};
