export function generateClassListPDF(options: {
  schoolName: string;
  className: string;
  academicYear: string;
  students: { firstName: string; lastName: string }[];
}): boolean {
  const { schoolName, className, academicYear, students } = options;

  const studentListHTML = students
    .map(
      (s, i) => `
        <div class="student-item">
          <span class="student-number">${i + 1}.</span>
          <span>${s.firstName} ${s.lastName}</span>
        </div>
      `
    )
    .join("");

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${className} - Class List</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            padding: 40px;
            color: #1a1a1a;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1E3A8A;
            padding-bottom: 20px;
          }
          .school-name {
            font-size: 22px;
            font-weight: 700;
            color: #1E3A8A;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          .class-title {
            font-size: 18px;
            font-weight: 600;
            color: #0EA5E9;
            margin-top: 8px;
          }
          .academic-year {
            font-size: 14px;
            color: #64748b;
            margin-top: 4px;
          }
          .student-list {
            margin-top: 24px;
          }
          .student-item {
            padding: 8px 12px;
            border-bottom: 1px solid #f1f5f9;
            font-size: 14px;
          }
          .student-item:last-child {
            border-bottom: none;
          }
          .student-number {
            font-weight: 600;
            color: #1E3A8A;
            margin-right: 8px;
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
          }
          @media print {
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="school-name">${schoolName}</div>
          <div class="class-title">${className}</div>
          <div class="academic-year">${academicYear}</div>
        </div>
        <div class="student-list">
          ${students.length === 0
            ? '<p style="text-align:center;color:#94a3b8;padding:20px;">No students enrolled.</p>'
            : studentListHTML
          }
        </div>
        <div class="footer">
          Generated by EduGrade | ${academicYear}
        </div>
      </body>
    </html>
  `;

  const printWindow = window.open("", "_blank", "width=800,height=600");
  if (!printWindow) {
    return false;
  }
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 300);
  return true;
}
